cypress/unit/store-getter-getColumnDescription.cy.js, cypress/unit/store-getter-getValueDescription.cy.js, cypress/unit/store-getter-isPageAccessible.cy.js, store/index-refactor.js
Co-authored-by: Sebastian Urchs <surchs@users.noreply.github.com>
Closes #300
=> Update to Vuex syntax for getters and unit tests

assets/css/main.css, components/category-select-table.vue, components/column-linking-table.vue, cypress/component/category-select-table.cy.js, cypress/component/column-linking-table.cy.js, cypress/component/index_page.cy.js, pages/categorization.vue, pages/index.vue, store/index-refactor.js
=> Components and their tests are nominally refactored for store

components/annot-columns.vue, cypress/component/annot-columns.cy.js, cypress/unit/store-mutation-alterColumnCategoryMapping.cy.js, cypress/unit/store-mutations-setDataDictionary.cy.js, store/index-refactor.js
=> Mutations should have a single payload parameter

store/index.js
Closes #308 
The simple addition of field `pageData` back into the store allows the annotation tool to launch.
=> Basic app launch post-refactor

README.md
Closes: https://github.com/neurobagel/annotation_tool/issues/46
=> Add node v16 dependency info

.github/workflows/lint.yaml, .husky/pre-commit, .lintstagedrc.json, package-lock.json, package.json
=> Added and configured lint staged and lint workflow

.github/workflows/cd.yaml, static/CNAME
=> Added and configured cd workflow

.github/workflows/test_e2e.yml
Specifying node version 16 for e2e testing
This addresses #369
=> e2e node version update

package-lock.json, package.json
=> Bumped cypress version to `12.9.0`

pages/download.vue
=> Refactored download button

.github/workflows/cd.yaml
- Changed `main` branch to `master` on push event in cd.yml
=> Updated cd.yaml

CITATION.cff, cff_validation.yml
Closes #478 
See also: https://github.com/Remi-Gau/neurobagel_api/blob/citation_cff/CITATION.cff
Changes proposed in this pull request: Add citation file for Zenodo processing/DOI citation.
=> Created citation file from template

components/tool-navbar.vue
- Updated navbar's documentation link 
For bug fixes:
=> [MAINT] Updated navbar documentation link

.github/dependabot.yml
=> [REF] Change dependabot default label

.github/dependabot.yml
Closes #531 
- Instructed dependabot to ignore semver-major for eslint-plugin-prettier
For bug fixes:
=> [MNT] Instructed dependabot to ignore semver-major for eslint-plugin-prettier

.github/workflows/test_component.yml, cypress/component/annot-explanation.cy.js, cypress/component/next-page.cy.js, package-lock.json, package.json
Closes #540 
- Removed the test case for checking next page's url, see [this comment](https://github.com/neurobagel/annotation_tool/issues/540#issuecomment-1719907990) for more details
- Includes changes from #536 
- Set the node version of cypress component test to 18 since the `annot-explanation.cy.js` was failing on default node version
For bug fixes:
=> [MNT] Removed the test case for checking next page's url

package-lock.json, package.json
Fixes #556
Closes #
-
-
For bug fixes:
=> [MNT] Remove uuid dependency

package.json
=> [ENH] Added lintfix script to package.json

components/annot-categorical.vue, cypress/component/annot-categorical.cy.js, cypress/e2e/app/simple-e2etest.cy.js, store/index.js
=> [ENH] Implemented annoatation workflow for healthy controls

.codespellrc, static/diagnosisTerms.json
=> [ENH] Added all valid diagnosis options

static/diagnosisTerms.json
=> [FIX] Updated diagnosisTerms.json

package-lock.json, package.json
=> [MNT] Bump vue from 2.6.14 to 2.7.15 and nuxt from 2.17.1 to 2.17.2

components/tool-navbar.vue
=> [ENH] Added logo to navbar

static/diagnosisTerms.json
=> [MNT] Updated `diagnosisTerms.json`

components/tool-navbar.vue
=> [ENH] Added `beta` badge to navbar

README.md
=> [DOC] Removed non-installation instructions/info from README.md

package-lock.json, package.json
This reverts commit 0ecbb051879a5124358708bf22d4fbc7c6d914c2.
It broke our e2e tests (only after PR went in) in ways we don't currently understand
- See https://github.com/neurobagel/planning/issues/110
- rollback https://github.com/neurobagel/annotation_tool/pull/678
-
For bug fixes:
=> [FIX] Revert "Bump core-js from 3.35.0 to 3.35.1 (#678)"

nuxt.config.js
=> [MNT] Add plausible

.github/dependabot.yml
=> [MNT] Instructed dependabot to ignore major version updates for `braces`

package-lock.json, package.json
Reverts neurobagel/annotation_tool#784
=> Revert "Bump bootstrap from 4.6.2 to 5.0.0"

.github/workflows/cd.yaml, README.md
- Closes #790 
- Updated deployment `cd` workflow to trigger on release instead of push to `main`
- Updated README.md with the mention of nightly deployment of the app
For bug fixes:
=> [MNT] Modified the deployment process to trigger on `release`

components/tool-navbar.vue
=> [FIX] Fix link to docs
