neurobagel/legacy_annotation_tool

- package-lock.json
- package.json
- pages/index.vue
Addresses #1 . Files may now be uploaded and are stored in `fileText` in landing page (index.vue)'s data. Temporary text area is set up for viewing of file text content - though currently not pretty printed.
> Ability to upload file and store it as data via landing page

- assets/css/main.css
- components/coloring-listgroup.vue
- components/filedata-table.vue
- pages/categorization.vue
- pages/index.vue
- store/index.js
1. Fix for preserving page state of categorization page - table is (re)painted on page load based on info in the store (see 3 below)
2. Retrieval of palette on page load (see `mounted()` in each page) from stylesheet and placement of palette in store for later use by JS components
- Current colors for table painting are immediately set afterward (`setCurrentPaintClass(0)` in `categorization.vue`) and placed in the store
3. Replacement of old way(s) of table painting with simplified method
- Table row is styled appropriately upon click
- Row ID is placed in store upon table row click and easily identified and repainted (see `paintTable()` in `categorization.vue`)
4. Removal of old and now-unused functions and data
5. General streamlining of landing and categorization pages/components
> Page state preservation for Categorization page, Palette/Table clicking simplification, and general cleanup for landing and categorization pages

- .eslintignore
- .eslintrc.js
- package-lock.json
- package.json
This adds:
- ESLint as a code linter
- vue specific ESLint rules and the corresponding plugins
- config for ESLint and ignore file
- prettier as a code formatter
- dependencies for all of this, plus dependencies for editorconfig (needs npm install in vscode to work)
This is related to what we discussed in #74.
I think there is a tradeoff between having something going now and immediately adopting a very strict style guide. I prepared some rules that I think would make sense to adopt eventually (e.g. airbnb style guide) but commented out for now. There are no linting checks to run the code, so all linting warning and errors can be ignored for now.
> [STYLE] add ESLint and prettier

- components/annot-age.vue
- components/annot-assessment.vue
- components/annot-diagnosis.vue
- components/annot-explanation.vue
- components/annot-gender.vue
- components/annot-sex.vue
- pages/annotation.vue
> [FEAT] add explanation component

- components/category-assessment.vue
- pages/annotation.vue
- store/index.js
Integrating the recent additions to the annotation page with the elements of the global store. 
- `columnToCategoryMap` and `dataTable` are now used by annotation page components.
-  `dataTable.original` is read by annotation page components and when annotation changes are made via `writeTable` on `annotation.vue` changes are made to `dataTable.annotated`
- `writeColumn` was rewritten to call the unlink column with category action from the store
- A fix was put into place where to align the name of the assessment category on the categorization page with the annotation page. It's called 'Assessment Tool'.
> Initial work to integrate annotation page components and global store

- layouts/default.vue
- pages/annotation.vue
- pages/categorization.vue
- pages/index.vue
- store/index.js
A layout vue template has been created in `layouts/default.vue` and `tool-navbar` has been moved outside of the pages and into that default layout.
As such pages are no longer responsible for generating the component and only have to worry about setting the current page via store function `setCurrentPage`.
The store now maintains a member `currentPage` for the navbar component.
> Creating a layout for the tool and moving navbar to the layout

- components/annot-discrete-choices.vue
- components/category-sex.vue
- nuxt.config.js
- package-lock.json
- package.json
- plugins/vue-select.js
This PR adds a drop-down based functionality for mapping discrete values to a set of available choices.
For now we use this only for the sex category
> [FEAT] add discrete value annotation

- components/annot-age-values.vue
- components/annot-discrete-choices.vue
- components/category-age.vue
- components/category-sex.vue
- pages/annotation.vue
- pages/download.vue
- store/index.js
This PR adds a basic download page that follows the annotation page. 
Currently it is always accessible from the annotation page (not unlocked upon completion of annotation - like the other pages). This is just for demo purposes. Going to the download page while in the annotation page without having 'annotated' any data merely produces a blank page with "download" button.
However, once an annotation has occurred, going to the download page produces a table of the "annotated" data.
NOTE: Some other aspects of this implementation should be revisited after the demo tomorrow - including how/when annotation status is saved in the store. This will include moving replicated functionality like the 'Confirm and Upload' button upwards out of the annotation page's components.
> Adding download page and hooking it into annotation tool workflow

- components/annot-vocabulary.vue
- components/category-assessment.vue
- components/category-diagnosis.vue
- pages/annotation.vue
- store/index.js
This PR adds a new annotation component (annot-vocabulary.vue) for
- diagnosis
- assessment tools
annotation.
The functionality at the moment is limited to freeform text fields without validation. 
For diagnosis,  every unique value is displayed and can be mapped to a term. The tooltip suggestions ask for SNOMED-CT.
For assessment tools, every column name labeled as "about assessment" can be mapped to a term, and no unique values are shown.
Closes https://github.com/metaneuro/annotation_tool/issues/63
Known limitations:
- the provided mappings are not (yet) tied to the global app state. So navigating away and back to the annotation page will reset all text fields
- similarly, the mappings (unique value -> vocabulary term, and column Name -> vocabulary term) are not emitted to the parent …
> [FEAT] add vocabulary annotation

- components/annot-age-values.vue
- components/annot-discrete-choices.vue
- components/annot-vocabulary.vue
- components/category-age.vue
- components/category-diagnosis.vue
- components/category-sex.vue
- pages/annotation.vue
- store/index.js
- Components get as props both the original dataTable and the annotated dataTable
- inside components the updated mappings of values are applied to the annotated dataTable in order not to lose previous annotations
- raw values are still displayed based on the original dataTable.
Fixes: #94
> [FIX] pass the original and annotated dataTable to components

- pages/download.vue
- store/index.js
The current condition we accept for an annotation to have occurred - and thus the download of a file to be available on the download page - is if any value in the annotated data table differs from its counterpart in the original data table.
> Changing annotation table status check to see if it differs from original table

- assets/css/main.css
- components/annot-age-values.vue
- components/annot-columns.vue
- components/annot-discrete-choices.vue
- components/annot-vocabulary.vue
- components/tool-navbar.vue
- pages/annotation.vue
- pages/download.vue
- store/index.js
This implements all of the changes as suggested in #93 - though there are still some places for whitespace improvements on the annotation page.
Also included is the stretching of the download page table to full size of the browser window.
> Styling improvements for demo

- components/annot-missing-values.vue
- components/annot-tab.vue
- layouts/default.vue
- pages/annotation.vue
- pages/categorization.vue
- store/index.js
I'm setting this initial version of the missing values component up as a PR. It's currently functional, but a code and functionality review is warranted.
> Initial missing values implementation

- components/annot-missing-values.vue
- components/annot-tab.vue
- pages/annotation.vue
- store/index.js
This PR implements the version of the missing value component we have discussed in #58. The component does not detect or create missing values, it only does two things:
- for the currently relevant column names, show the missing values currently kept in the global store
- provide a UI element (button) to declare any of these values as "not missing". this will trigger an event chain and update the global store by removing this value from the array of missing values of its columnName
Writing to `missingColumnValues` in the store via the `setMissingColumnValues` mutation was not reactive, because Vue doesn't track indexed changes to Objects (see https://v2.vuejs.org/v2/guide/reactivity.html). I have replaced the store logic with an `Object.assign` statement. This will continue to work with …
> Implement missing values component

- components/annot-age-values.vue
- components/annot-discrete-choices.vue
- components/annot-tab.vue
- pages/annotation.vue
- store/index.js
This PR implements the interface and logic to declare missing values in the discrete-values component (atm used for the sex category).
Criteria from the issue were:
Accept when:
The main addition here was making the state check for the "save annotation" button a computed property and turn all of its dependencies (e.g. `this.valueMapping`) reactive.
Resolves #120
> Implement missing values discrete

- components/annot-explanation.vue
- components/annot-tab.vue
- pages/annotation.vue
This PR is for two small fixes. 
The first is to supply the explanation component on annotation tabs with a unique ID so has consistent behavior - each explanation component on each tab acts like it is a separate object with its own expansion status.
The second is to replace the old `no-ssr` tag that is currently being used to overcome the duplicate annotation tab bug that @surchs discovered. The suggested `client-only` tag has replaced it. There is no discernible difference other than the deprecated `no-ssr` tag warning disappearing from the debug console.
Resolves #116 
Resolves #109
> Fixes for unique explanation component ID and client-only tags

- pages/download.vue
This changes the output format to the current data model.
This should have been tested as well, however as explained in the issue, writing a test for this is going to be pretty challenging as we either need to setup component tests with vuex, or handle file downloads. We should do that, but I thnk this change is small and important enough to go in before that. Let me know what you think.
Fixes #189
> Update output format to data model

- .github/workflows/main.yml
- components/annot-discrete-choices.vue
- cypress/component/annot-discrete-choices.cy.js
- cypress/support/commands.js
- cypress/support/component.js
- store/index.js
@surchs Opening this up as the fix for bug #176 is ready in the related commit.
[Edit: I will be following this commit up with a component test for `annot-discrete-choices`, so hold up on this PR review until that commit is in.)
There is also a question of establishing a UI paradigm regarding the 'Save Annotation' button. See below.
**Fix description**
The issue lay in how the `applyAnnotation` function in `annot-discrete-choices.vue` sets new values. Once a new annotation value is saved it is set in the annotated table and we can no longer rely on the value in that table to help us find a newly set value in the `valueMapping` object. The latter is updated every time a new selection is made by the user (via the `updateMapping` function).
So, what was needed is 1 (or possibly 2) additions …
> Fix for categorical double save bug on annotation page

- components/file-selector.vue
- pages/index.vue
This bug fix addresses issue #194. Before, selecting a data table file (`participants.tsv`) and then attempting to select a second file but instead cancelling in the file select dialog resulted in a JS error and page crash.
Once this crash was initially addressed, it also revealed that the code would wipe the first data table selection (as well as its filename and file preview in the UI). 
Neither of these issues occurred for the data dictionary file selection.
Expected behavior:
The above was addressed by creating a cleaner check against file select event's file data and by not resetting the file data variable if no new file has been selected. (See `onFileSelected` in `file-selector.vue`.)
I also cleaned up some conditional checks for possible values of the file data variable `fileInput` …
> File select cancellation fix + condition cleanup

- components/annot-explanation.vue
- cypress/component/annotation-explanation.cy.js
- package-lock.json
- package.json
- added component test to illustrate prop behavior minor refactoring:
- use uuid package to ensure random ID instead of passing unique ID as prop
- minor refactor of variable names
closes #211
> Explanation component test added

- components/annot-missing-values.vue
- cypress/component/annot-missing-values.cy.js
Missing value component:
- receives currently active category (e.g. "age") via prop (from a parent component)
- receives a filtered view of missing values from the store via getter
- can look up the description of a value in the store via getter (as before)
- informs the store of a change to the missing values via a mutation call to the store
Component test:
- checks that the component likes the data provided to it
- ensures that component actually calls the mutation with the right parameters
closes #212
> Refactor and test missing value component

- components/category-select-table.vue
- cypress/component/category-select-table.cy.js
Newly refactored category select table on the categorization page...
1. has required input (`categories`, `categoryClasses`) directly from the store 
2. former `instructions` and `title` props have also been removed, relegated to the new refactored categorization page that will act more like a layout.
3. `selectedCategory` is still emitted to the categorization page (which maintains a `currentCategory` field to share between the `category-select-table` and the `column-linking-table`)
The component test...
1. Mocks store required input via getters
2. Runs through selection of all the default categories.
3. Spies for the emitted selected category output
> Refactor of category-select-table component

- components/annot-columns.vue
- cypress/component/annot-columns.cy.js
> Refactored annot-columns component so it's ready for the store

- assets/css/main.css
- components/next-page.vue
- components/tool-navbar.vue
- cypress/e2e/page/categorization-pagetests.cy.js
- cypress/support/commands.js
- layouts/default.vue
- pages/annotation.vue
- pages/categorization.vue
- pages/download.vue
- pages/index.vue
- store/index.js
This PR represents changes that we have planned for I/O refactor for the annotation tool's pages but also our refactor next page accessibility/the navbar and default layout.
Since most of these changes are interlinked, it made sense to include them in one PR. This is also a "in the dark" PR given that we have no good means of testing the following changes throughout the app because of the ongoing refactor. This ties together issues #232, #218, #214, #215, #216, and #217.
So the code review for this will be more of a visual inspection of the changes made. (I will leave it as a draft for now as @surchs may continue this work next week while I am away.)
Below is a summary of the changes made thus far.
**Next page and Layout**
This is a new component that sits on the bottom right of the …
> Next page accessibility/navbar/layout refactor + All page refactor

- components/annot-tab.vue
- cypress/component/annot-tab.cy.js
Took over this PR from @jarmoza because this component was the last small component to be refactored (rest are pages and I/O things)
Note: the component tests are visually empty because the `annot-tab` component is just a container component for the components displayed on the annotation page. 
The component now has no internal logic or state because it's child components talk directly to the store. The only thing it is passing along is the prop for the `activeCategory`.
Closes #207
> Refactor annotation-tab component 

- components/next-page.vue
- store/index.js
Upon review, it's apparent that the `nextPageAccessible` getter can be removed from the store and its usage in the `next-page` component.
This same functionality can be accessed by calling getter `pageAccessible` with the return value of getter `nextPage` as an argument.
> Removal of nextPageAccessible getter

- components/annot-columns.vue
- components/column-linking-table.vue
- cypress/component/annot-columns.cy.js
- cypress/component/column-linking-table.cy.js
- cypress/unit/store-mutation-alterColumnCategoryMapping.cy.js
- store/index-refactor.js
> Implemented mutation to change column to category mapping

- components/category-select-table.vue
- cypress/component/category-select-table.cy.js
- cypress/unit/store-getter-getCategories.cy.js
- cypress/unit/store-getter-getCategoryNames.cy.js
- store/index-refactor.js
> Implement getCategories store getter

- components/column-linking-table.vue
- cypress/component/column-linking-table.cy.js
- cypress/unit/store-getter-getColumnDescription.cy.js
- store/index-refactor.js
There is a bit more in this PR than just the normal refactor. The reason is that adding a new test for the 
`column-linking-component` somehow broke the existing component test in a way I didn't understand.
The original `column-linking-component` test passed when forced to run alone `it.only`, but could not wrap the
`commit` function on the `store` object in a `cy.spy` when it was run second after the new test. 
I think this may be because running the first test somehow changes the mocked `store` object in a way
that affects subsequent test. I was not able to debug this though, the `store` object looked normal to me.
As a workaround, I have moved the mocked store into a `beforeEach` statement to make sure every test
gets passed the same `store` object. 
There may be better ways of doing …
> Implement getColumnDescription getter

- components/annot-categorical.vue
- components/annot-missing-values.vue
- cypress/component/annot-categorical.cy.js
- cypress/component/annot-missing-values.cy.js
- cypress/unit/store-getter-getValueDescription.cy.js
- store/index-refactor.js
> Implement value description getter

- components/column-linking-table.vue
- cypress/component/column-linking-table.cy.js
- cypress/unit/store-getter-getColumnNames.cy.js
- package.json
- store/index-refactor.js
> Implemented getColumnNames getter 

- cypress/unit/store-mutation-setCurrentPage.cy.js
- store/index-refactor.js
This is a straightforward implementation for both the mutation and test. The mutation itself is currently only used by the `tool-navbar` and the `next-page` components.
This addresses #265
> setCurrentPage mutation + unit test for store refactor

- components/next-page.vue
- cypress/unit/store-getter-getNextPage.cy.js
- store/index-refactor.js
This PR addresses #260. This getter makes use of the annotation tool's implicit page order. E.g. Given the current page of the app, what is the next (or following) page?
The `next-page` component has been altered to make use of the new getter name style `get*`.
The unit test sets each page as the current page and makes sure the proper 'next page' is being returned from the getter.
> Implementation of nextPage getter for refactor + unit test

- cypress/component/index_page.cy.js
- cypress/fixtures/examples/good/example_short.json
- cypress/fixtures/examples/good/example_short.tsv
- pages/index.vue
Closes #298
Co-authored-by: Jonathan Armoza <jarmoza@gmail.com>
> index page refactor

- components/next-page.vue
- components/tool-navbar.vue
- cypress/unit/store-getter-isPageAccessible.cy.js
- store/index-refactor.js
This PR addresses #261.
The implementation of this boolean getter is a bit more complex than most in our store. `isPageAccessible` is a tweaked version of `pageAccessible` from the previous store. It checks the conditions necessary for access to the given page passed to it.
The tweaks from `pageAccessible` reflect the current state of the implementation of the categorization page (where assessment tools and tool groups are to be reimplemented soon). Currently one should only need at least one category-linked column and for the 'Subject ID' category to be used at least once to progress to the `annotation` page. Secondly, since we do not yet have a good conditional metric for moving to the `download` page, a value `annotationCount` is used. (To move to the categorization page, a non-empty …
> Implementation of isPageAccessible getter for refactor

- cypress/unit/store-action-processDataTable.cy.js
- cypress/unit/store-mutation-initializeDataDictionary.cy.js
- cypress/unit/store-mutation-setDataTable.cy.js
- store/index-refactor.js
Closes #256 
This PR adds:
- the `processDataTable` action (#256)
- and also a new mutation `setDataTable` to process and then store a provided dataTable
- and also a new mutation `initializeDataDictionary` to create a skeleton data dictionary from a stored dataTable
with tests. The two mutations are meant to be called only from inside the store. There isn't anything to prevent a component to call the mutations directly (other than us not doing that). 
The test for the action is very limited, it only checks if the correct mutations are being committed. The reason behind this is that because the mutations are already tested via their unit tests, and because they are mocked during the unit test of the action, it would be pretty tricky to test that the action actually has the desired effect …
> action to process a new dataTable

- components/next-page.vue
- components/tool-navbar.vue
- store/index.js
Closes #315 and #317
Some agent in the tool must be responsible for indicating that a page is accessible to the user (on the page via user action, or at some higher level like the navbar or layout, etc.) Previously, actions on a page by a user would manually change the accessibility status of the next page (via an action call to change `pageData.<pageName>.accessible`).
The navbar now keeps a watch on the store for changes, updating the accessible status of pages via `updatePageDataAccessibility` as the relevant changes are made to the store that would unlock them. This has the side effect of also keeping the next page button status on each page up to date with the state of the store.
The more complex Vuex getter `isPageAccessible` could not be reactive because it currently returns a …
> Navbar/next page button/page accessibility update for refactor

- components/file-selector.vue
- components/tool-navbar.vue
- cypress/component/index_page.cy.js
- pages/index.vue
- store/index.js
This closes #314 and #320 
Several updates here are made for the index page relating to the recent store refactor.
1. The workflow for the user has changed in that they are no longer able to select a data dictionary without first having selected a data table. This has been accomplished by adding a new feature to `file-selector` care of the prop `enabled`. File selection for a data dictionary is disabled until a data table has been selected. 
2. `textarea` elements on the index page have been converted to one way binding (user input does not edit underlying value) via the `value` attribute instead of the two-way bind via `v-model`
3. Reactivity for the textarea for the data dictionary input has been fixed by reassigning the data dictionary to itself in the store's `setDataTable` mutation …
> Updates to Index page for data table + data dictionary for store refactor

- components/annot-continuous-values.vue
- cypress/component/annot-continuous-values.cy.js
- cypress/unit/store-mutation-setHeuristic.cy.js
- store/index.js
This PR addresses #270.
1. `setHeuristic` is now a mutation that takes a column and heuristic name and assigns the heuristic to the `transformationHeuristic` field in the data dictionary object for that column
2. A unit test has been created for the new `setHeuristic` mutation.
3. The `annot-continuous-values` component has been amended to understand `setHeuristic` as a mutation instead of an action.
> New mutation setHeuristic for phase 2 store refactor

- components/annot-continuous-values.vue
- cypress/component/annot-continuous-values.cy.js
- cypress/unit/store-getter-getHeuristic.cy.js
- store/index.js
This completes #266.
1. getter `getHeuristic` returns the `transformationHeuristic` assigned to a particular column in `dataDictionary.annotated`. If the given column has no `transformationHeuristic` key, a blank string is returned
2. Unit tests in `store-getter-getHeuristic.cy.js` test for both of the above scenarios.
3. The naming of the getter is updated in the `annot-continuous-values` component, `getActiveHeuristic` -> `getHeuristic`. The reasoning here is that 'active' referred to the operative heuristic for a particular category, and now that heuristics can vary across columns this is no longer the case.
Moves us one step closer to #336.
> New 'getHeuristic' getter for phase 2 store refactor

- cypress/unit/store-getter-getAnnotationComponent.cy.js
- store/index.js
This closes #267.
There is now a getter to retrieve what was once `specializedComponent` in the `annotationDetails` list in the store.
Now the `componentName` (currently `annot-continuous-values` or `annot-categorical`) is listed alongside each category in the `categories` object.
This implementation is accompanied by 3 unit tests for the current categories that are operative on the annotation page: 'Age' (continuous values), 'Sex' and 'Diagnosis' (categorical). There is currently no component for the 'Subject ID' category as this requires no annotation.
> Refactor getter 'getAnnotationComponent'

- cypress/unit/store-getter-getMappedColumns.cy.js
- store/index.js
This closes #273.
A new getter, `getMappedColumns` has been introduced to the store that retrieves a list of columns given a category.
Two unit tests for this getter have been implemented as well, one that looks for a correct list of columns and another that looks for an empty list given a category to which no data table columns have been linked.
> getMappedColumns Getter for Phase 2 Store Refactor

- components/annot-missing-values.vue
- cypress/unit/store-getter-getMissingValues.cy.js
- store/index.js
This closes #278.
This PR implements a getter for retrieving any values that have been marked as "missing' for a particular given column in the annotated data dictionary. The expectation is that if there are any missing values they will be stored in `dataDictionary.annotated.<columnName>.missingValues`.
Also implemented are unit tests for three scenarios for this getter:
1. Retrieving the missing values list from`dataDictionary.annotated.<columnName>.missingValues`
2. Returning an empty list if there are no missing values (no `missingValues` key) in the column entr in the `dataDictionary.annotated` object
3. Returning an empty list if the column itself is not listed in `dataDictionary.annotated`
This is related to #275 - which will be implemented following this PR.
> Getter getMissingValues for Phase 2 Store Refactor

- components/annot-missing-values.vue
- cypress/component/annot-missing-values.cy.js
This PR
1. Simplifies the implementation of the `tableItems` function in the `annot-missing-values` component
1. Fixes the `annot-missing-values` component test that was broken by #355 (a name change for the use of the `getMissingValues` getter in `annot-missing-values`).
2. Formats the `annot-missing-values` component test
> Missing values table items refactor + component test fix

- components/annot-categorical.vue
- cypress/component/annot-categorical.cy.js
- cypress/unit/store-getter-getUniqueValues.cy.js
- store/index.js
This PR closes #277 by implementing the following:
1. `getUniqueValues` getter in the store that takes every column linked to a given category and gathers unique values for each column via the `dataTable`. The getter outputs an object keyed on column with values that are an array of the unique values for that column. Missing values are skipped via lookup in the `dataDictionary`
2. `getUniqueValues` also takes an optional parameter `maxValues` to limit how many values are returned
3. `displayItems` in the `annot-categorical` component has been rewritten to accommodate the new output of `getUniqueValues`
4. Unit tests for this getter in `store-getter-getUniqueValues.cy.js` test the following scenarios: a) unique values for a single column, b) unique values for multiple columns, c) …
> getUniqueValues getter for Phase 2 Store Refactor

- cypress/unit/store-mutation-changeMissingStatus.cy.js
- store/index.js
This PR closes #171  and #364 by implementing the following:
1. Ensuring missing values are added/removed from the `missingValues` list that will exist for each column in `dataDictionary.annotated`
2. Add a uniqueness check to the add value case in `changeMissingStatus`
3. Updating unit tests for `checkMissingStatus` to properly add/remove from `missingValues` lists
4. Additional unit test to ensure no duplicate values can be added to the `missingValues` list in `dataDictionary.annotated.<column>`.
> changeMissingStatus getter Fix + Check for Unique Values

- components/annot-categorical.vue
- cypress/component/annot-categorical.cy.js
- cypress/unit/store-mutation-selectCategoricalOption.cy.js
- store/index.js
This PR closes #274 by implementing the following:
1. `selectCategoricalOption` mutation in the store that takes a column name, option value and raw value and a) creates a `valueMap` object on `dataDictionary.annotated.<column_name>` if it does not exist, and b) assigns the raw value and option value as a key/value pair in the `valueMap` object.
2. Three unit tests in `store-mutation-selectCategoricalOption.cy.js` that test a) if the value map is created when it does not yet exist, b) if the option (annotated) value is set in the value map for the raw value, and c) ensures a previously entered option value can be overwritten in the value map.
3. `annot-categorical` component and its component test in `annot-categorical.cy.js` are updated to reflect changes for the new …
> selectCategoricalOption mutation for Phase 2 Store Refactor

- .github/workflows/test_e2e.yml
- components/annot-continuous-values.vue
- cypress/component/annot-continuous-values.cy.js
- cypress/unit/store-getter-getHarmonizedPreview.cy.js
- store/index.js
This addresses #272 by implementing the following:
1. The creation of new store getter `getHarmonizedPreview` which takes a column name and a data table value and produces a transformed version of that value given the transformation heuristic assigned to the given column. Of note, for this new implementation of functionality that was contained in the previous component `annot-age-values` is that `isoyear` transformation is currently being left (commented) out so it can be more fully addressed in a more robust way in its own new issue.
2. The introduction of the `appSetting` store field as mentioned in our Miro board draft of the store refactor. Currently this only contains the `missingValueLabel` for the `'string'` transformation heuristic.
3. Tests for each different transformation …
> getHarmonizedPreview getter for Phase 2 Refactor

- components/annot-continuous-values.vue
- cypress/component/annot-continuous-values.cy.js
- store/index.js
This PR implements #336.
1. The `annot-continuous-values` component (that is used on the annotation page tab, currently exclusively for 'Age'-categorized columns) now features one tab per column
2. Each tab lists the data for that column with an original value and preview value column
3. Each contains a dropdown featuring all of the app's transformation heuristics for continuous values - including a default blank with which no transformation has yet taken place
4. Unit tests in `annot-continuous-values.cy.js` have been reworked and extended for the new feature
NOTE: @rmanaem There was something happening in the testing that I could not explain. The reason that the `store` variable is initialized each time in the `beforeEach` function is because its function definitions in `store.getters` …
> Feature for Phase 2 Refactor: Transform Heuristics for continuous values are now selectable by column

- components/annot-categorical.vue
- cypress/component/annot-categorical.cy.js
- cypress/unit/store-getter-getCategoricalOptions.cy.js
- cypress/unit/store-mutation-selectCategoricalOption.cy.js
- store/index.js
Closes #371
- controlled terms are now handled as objects with `{label: "human readable label", identifier: "https://example.org/vocab/termID"}`
- the categorical annotation component and all involved tests are updated. This mostly meant changing the way vue-select handles data to objects. See: https://vue-select.org/guide/values.html#transforming-selections
- the hard-coded controlled terms in the store (for now only "sex") have been updated to correspond to this format
Overall the changes are limited, because the code can mostly just handle terms as objects already.
Two things to note:
1. Right now, we still store only a string literal in the valueMapping part of the dataDictionary, but now we store the identifier and not the label. In the future we might store the complete term object …
> Refactor: handle controlled terms as objects

- components/annot-categorical.vue
- components/annot-continuous-values.vue
- components/annot-tab.vue
- cypress/component/annot-categorical.cy.js
- cypress/component/annot-continuous-values.cy.js
- cypress/e2e/page/categorization-pagetests.cy.js
- cypress/unit/store-getter-getMappedCategories.cy.js
- cypress/unit/store-getter-isPageAccessible.cy.js
- cypress/unit/store-mutation-selectCategoricalOption.cy.js
- pages/annotation.vue
- store/index.js
In an effort to keep PRs small, this PR closes the first step of restoring the annotation page (access + tabs) now that the second phase of our store refactor is (mostly) complete. As such this PR is not yet testable via our e2e page tests since the annotation page itself is functionally incomplete and its related e2e tests need to also be refactored to adapt to changes we have made. (Closes #348.)
In addition to basic access to the page with its primary components loading, this PR also addresses the following, as noted in #347 : 
- Tabs now must look at new store configuration for info on their construction (previously in store field annotationDetails)
Here is a file by file explanation of the changes made thus far:
`annot-categorical.vue`
- `v-select` value attribute is temporarily …
> Phase 2 Store Refactor - Integration Part 1 - Annotation page access, tabs refactor, column-category unlinking

- cypress/unit/store-mutation-alterColumnCategoryMapping.cy.js
- store/index.js
This PR implements #376.
Unit tests for `alterColumnCategoryMapping` now use a `beforeEach` to load up a `store` object and new tests for the above implementation have been added.
> Phase 2 refactor: Column linking/unlinking alters data dictionary

- components/annot-categorical.vue
- cypress/component/annot-categorical.cy.js
- store/index.js
There were two remaining instances of `getSelectedOption` after PR #377 that were breaking the app when manually running through to the annotation page. (They would have been noticed with the integration test for the annotation page enabled.)
In addition, after that a bug was discovered in the improper use of the optional chaining `?.` syntax in the new `getSelectedCategorical` getter. The operator before array `[]` syntax is still `?.`
> Replace remaining getSelectedOption instances and fix optional chaining bug with new getter

- components/annot-categorical.vue
- components/annot-continuous-values.vue
- cypress/component/annot-categorical.cy.js
- cypress/component/annot-continuous-values.cy.js
- cypress/unit/store-mutation-updateAnnotationCount.cy.js
- store/index.js
This PR includes:
- Implementation of `updateAnnotationCount` mutation
- A categorical column is considered annotated if:
- It contains `valueMap`
- Its `valueMap` is not empty
- A continuous column is considered annotated if:
- It contains `transformationHeuristic`
- Its `transformationHeuristic` is not `null`
- `updateAnnotationCount` unit-test
- Modification made to `selectCategoricalOption` mutation, if the empty option from the v-select is selected `rawValue` is removed from the `valueMap`
Closes #388
> Implemented `updateAnnotationCount` mutation

- cypress/unit/store-getter-getColumnDescription.cy.js
- cypress/unit/store-mutation-initializeDataDictionary.cy.js
- store/index.js
This PR includes the fix for the bug outlined in #384.
Changes include changing `description` references to `Description` in
- index.js
- store-mutation-initializeDataDictionary.cy.js
- store-getter-getColumDescription.cy.js
Closes #384
> Capitalized references of `description` in store and updated affected unit tests

- layouts/default.vue
- store/index.js
This PR includes the fix for #394. 
Changes include:
- Implemented a case for the download page in the switch statement of `getNextPage` getter in `index.js`
- Implemented condition for displaying `next-page` component in `default.vue` layout component
Closes #394
> Fixed the bug that made download page unreachable from annotation page

- components/annot-categorical.vue
- components/annot-columns.vue
- components/annot-continuous-values.vue
- components/column-linking-table.vue
- cypress/component/annot-columns.cy.js
- cypress/component/annot-continuous-values.cy.js
- cypress/component/column-linking-table.cy.js
- cypress/unit/store-getter-getHeuristic.cy.js
- cypress/unit/store-getter-getSelectedCategoricalOption.cy.js
- cypress/unit/store-mutation-alterColumnCategoryMap.cy.js
- cypress/unit/store-mutation-selectCategoricalOption.cy.js
- cypress/unit/store-mutation-setHeuristic.cy.js
- cypress/unit/store-mutation-updateAnnotationCount.cy.js
- store/index.js
This PR addresses both #386 and #390. A list of changes made by file below.
**annot-categorical.vue**
- Removed `label` attribute for `v-select` as it was unnecessary and producing a warning. `value` is used for showing what was just selected and retrieving what had been selected upon component re-mount
- Added component function `selectOptionAndUpdate` as we would like to avoid multiline attribute code
**annot-continuous-values.vue**
- Added component function `selectHeuristic` as we would like to avoid multiline attribute code
**index.js**
_Formatting/streamlining_
- Added a comment to describe the new annotation count store field
- Small streamlining of `getColumnDescription`, `getHarmonizedPreview` implementation
- `updateAnnotationCount` - Updated this function for a clean check of …
> Categorical Select bugfix + Rework of initialization of data dictionary columns for data types

- cypress/component/annot-continuous-values.cy.js
- cypress/unit/store-getter-getHarmonizedPreview.cy.js
- cypress/unit/store-getter-getTransformOptions.cy.js
- store/index.js
This PR includes the implementation of the fix for #392.
Changes include:
- Removal of the `range` and `string` options from `transformationHeuristics` in `index.js`
- Update of affected tests:
- `annot-continuous-values.cy.js`
- `getHarmonizedPreview.cy.js`
- `getTransformOptions.cy.js`
Closes #392
> Removed `range` and `string` options from `transformationHeuristics`

- pages/download.vue
This PR closes #399 by doing the following:
* The table used to show the former annotated data table has been removed
* Associated methods used to build the JSON for output download have been removed
* Some functionality left in but commented out as a guide for update to new annotated data dictionary download code and possible new preview textbox for the annotated data dictionary
* Code cleanup + updated comments
> Removal of old download components and related functionality

- components/next-page.vue
- cypress/component/next-page.cy.js
(cherry picked from commit 443f742333fb34dea1c107f4d86fa215ab4bbc19) Remaking this PR off a clean branch from [dev](https://github.com/neurobagel/annotation_tool/tree/dev_components_talk_to_store_directly). 
This PR closes https://github.com/neurobagel/annotation_tool/issues/412.
As mentioned in the issue, the following tests have now been implemented for the next-page component:
* Does the label on next page button correspond to the current page (This is tested across home, categorization, and annotation pages – where a 'next page' button exists.)
* Does next page disabled status correspond to page accessibility
* When clicked is setCurrentPage mutation fired once with the correct parameters
> Next page button component tests - Clean branch

- cypress/unit/store-getter-getCategoricalJsonOutput.cy.js
- store/index.js
> Getter for json output for discrete (categorical) value columns

- cypress/unit/store-getter-getCategoricalJsonOutput.cy.js
- cypress/unit/store-getter-getContinousJsonOutput.cy.js
- cypress/unit/store-getter-getTransformOptions.cy.js
- store/index.js
Closes #407 
- Modified `transformationHeuristics` according to this [comment](https://github.com/neurobagel/annotation_tool/issues/407#issuecomment-1553385867)
- Updated `getTransformOptions` getter
- Updated `getTransformOptions` getter's unit test
- Implemented `getContinuousJsonOutput` getter
- Implemented unit test for `getContinuousJsonOutput` getter
- Removed unnecessary test cases from `getCategoricalJsonOutput` getter's unit test
For bug fixes:
> [ENH] Implemented getter to create JSON representation of continuous column

- .github/dependabot.yml
Closes #454 
See also #453
- Updated dependabot.yml to ignore nuxt and vue major version updates
For bug fixes:
> [MAINT] Instructed dependabot to ignore nuxt and vue major updates

- .github/dependabot.yml
Closes #464
See also #457 
- Update dependabot.yml to ignore webpack major version updates
For bug fixes:
> [MAINT] Instructed dependabot to ignore webpack major version updates

- components/tool-navbar.vue
- pages/index.vue
Closes #444 and #445 
See also [https://github.com/neurobagel/query-tool/issues/103](https://github.com/neurobagel/query-tool/issues/103) and [https://github.com/neurobagel/query-tool/issues/117](https://github.com/neurobagel/query-tool/issues/117)
To align with the new, cross-Neurobagel navbar shortcuts and styling, the following changes have been made to the annotation tool:
1. New and resized title: "Neurobagel Annotate"
2. New subtitle underneath title ("Harmonize phenotypic data")
3. Both title and subtitle link to [neurobagel.org](neurobagel.org)
4. New set of navbar shortcuts to the right of the annotation workflow (Home - Download) have been added separated by a vertical pipe character
5. The new navbar shortcuts include `v0.2.0` linking to the [release notes of the current …
> [ENH] Updated branding and shortcuts for navbar

- components/tool-navbar.vue
- nuxt.config.js
- plugins/bootstrap-vue.js
Closes #505 
- Added `BootstrapVueIcons` to the bootstrapvue plugin file
- Added appzi 
- Removed the `Feedback` navitem 
For bug fixes:
> [ENH] Added appzi

- package-lock.json
- package.json
This reverts commit cf85669db159695362211ddfba16a96f0a9039a7.
Reverting this bump as it breaks the nuxt node server when the tool is run in dev mode.
Related #531 
For bug fixes:
> Revert "Bump eslint-plugin-prettier from 4.2.1 to 5.0.0 (#513)"

- README.md
- cypress/unit/store-getter-getContinousJsonOutput.cy.js
- cypress/unit/store-getter-getJsonOutput.cy.js
- cypress/unit/store-getter-getTransformOptions.cy.js
- store/index.js
> [MNT] Capitalized age heuristics

- components/tool-navbar.vue
- cypress/unit/store-getter-getUniqueValues.cy.js
- store/index.js
Closes #568 
- Added `Assessment Tool` to the `categories` object in store state
- Implemented `getColumnsForCategory` and `getUniqueColumnValues`
- Refactored `getUniqueValues` and moved some of its logic to the newly implemented getters
For bug fixes:
> [MNT] Implemented `getColumnsForCategory` and `getUniqueColumnValues`

- cypress/e2e/page/download-pagetests.cy.js
- store/index.js
Closes #477
- Updated `alterColumnCategoryMapping` mutation to add the column mapped to `Subject ID` to the annotated data dictionary in the state
- Update `getJSONOutput` getter to add `participant_id` to the output file
- Expanded `download-pagetests` to check for `identifies` property and its value under `participant_id` key of the output file
For bug fixes:
> [ENH] Added `Subject ID/Participant ID` to JSON output file

- components/annot-tool-groups.vue
- cypress/e2e/app/simple-e2etest.cy.js
- cypress/unit/store-getter-getAssessmentToolJSONOutput.cy.js
- store/index.js
> [ENH] Added `Assessment Tool` annoatatoins to the JSON output file

- components/next-page.vue
- components/tool-navbar.vue
- cypress/e2e/page/my_happy_annotation-page_tests.cy.js
- store/index.js
Closes #545 
- Implemented `navigateToPage` action
- Replaced the implicit routing using `to` prop on buttons with a call to `navigateToPage` action on `click` event 
- Updated `my_happy_annotation_page` e2e test
For bug fixes:
> [MNT] Reworked routing for the app

- components/category-select-table.vue
- components/category-toolgroup.vue
- cypress.config.js
- cypress/e2e/app/simple-e2etest.cy.js
- cypress/e2e/page/annotation-pagetests.cy.js
- cypress/e2e/page/categorization-pagetests.cy.js
- cypress/e2e/page/download-pagetests.cy.js
- cypress/e2e/page/index-pagetests.cy.js
- cypress/support/commands.js
- pages/categorization.vue
- test_contributions.md
> [ENH] Aligned assessment tool workflow UI elements

- README.md
- Related to https://github.com/neurobagel/planning/issues/41
-
-
For bug fixes:
> [DOC] Add link to docs

- README.md
- components/annot-explanation.vue
- components/next-page.vue
- store/index.js
> [MNT] Updated help text and category explanations of the annotation page

- components/annot-single-tool.vue
- cypress/component/annot-tool-single.cy.js
> [ENH] Implemented styling for table rows of `annot-single-tool` component

- assets/css/main.css
- cypress/e2e/page/categorization-pagetests.cy.js
- pages/annotation.vue
- store/index.js
- Closes #663 
- add `Session ID` as a category
- add new color for session id
- make sure session ID does not count as an annotation and does not get its own annotation workflow (like Subject ID)
- add a simple e2e test to make sure of this
Note: this should probably have more extensive tests, I went for a basic test because we may soon refactor the app. But could add appropriate tests as well.
For bug fixes:
> [ENH] Add session ID as a new category for annotation

- README.md
- pages/download.vue
- pages/home.vue
Changes proposed in this PR:
- Update links to https://neurobagel.org
For bug fixes:
> [FIX] Update outdated docs links
